config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :hard_drives
  resources :rams
  resources :cpus
  resources :laptop_brands
  resources :laptop_orders
  resources :laptops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages

  root to: "laptops#index"


  resources :users
end

app/models/cpu.rb
class Cpu < ApplicationRecord
  has_many :laptops
  validates :name, presence: true
end

app/controllers/cpus_controller.rb
class CpusController < ApplicationController
  load_and_authorize_resource # run cancancan authorization before every method
  before_action :authenticate_user!
  before_action :set_cpu, only: %i[show edit update destroy]

  # GET /cpus
  # GET /cpus.json
  # Get all CPU entries and send them to INDEX view
  def index
    @cpus = Cpu.all
  end

  # GET /cpus/1
  # GET /cpus/1.json
  def show; end

  # GET /cpus/new
  # Create a new empty CPU entry and send it to NEW view
  def new
    @cpu = Cpu.new
  end

  # GET /cpus/1/edit
  def edit; end

  # POST /cpus
  # POST /cpus.json
  def create
    @cpu = Cpu.new(cpu_params)

    respond_to do |format|
      # Check if newly created CPU was saved in database, if it was flash a success message, if not flash a error message
      if @cpu.save
        format.html { redirect_to @cpu, notice: 'Cpu was successfully created.' }
        format.json { render :show, status: :created, location: @cpu }
      else
        format.html { render :new }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpus/1
  # PATCH/PUT /cpus/1.json
  def update
    respond_to do |format|
      # Check if updated CPU was saved in database, if it was flash a success message, if not flash a error message
      if @cpu.update(cpu_params)
        format.html { redirect_to @cpu, notice: 'Cpu was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpu }
      else
        format.html { render :edit }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpus/1
  # DELETE /cpus/1.json
  def destroy
    @cpu.destroy
    respond_to do |format|
      format.html { redirect_to cpus_url, notice: 'Cpu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cpu
    @cpu = Cpu.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cpu_params
    params.require(:cpu).permit(:name)
  end
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/views/cpus/_form.html.erb
<%= form_with(model: cpu, local: true) do |form| %>
  <% if cpu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cpu.errors.count, "error") %> prohibited this cpu from being saved:</h2>

      <ul>
        <% cpu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cpus/edit.html.erb
<h1>Editing Cpu</h1>

<%= render 'form', cpu: @cpu %>

<%= link_to 'Show', @cpu %> |
<%= link_to 'Back', cpus_path %>

app/views/cpus/index.html.erb
<h1>Cpus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cpus.each do |cpu| %>
      <tr>
        <td><%= cpu.name %></td>
        <td><%= link_to 'Show', cpu %></td>
        <td><%= link_to 'Edit', edit_cpu_path(cpu) %></td>
        <td><%= link_to 'Destroy', cpu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cpu', new_cpu_path %>

app/views/cpus/new.html.erb
<h1>New Cpu</h1>

<%= render 'form', cpu: @cpu %>

<%= link_to 'Back', cpus_path %>

app/views/cpus/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cpu.name %>
</p>

<%= link_to 'Edit', edit_cpu_path(@cpu) %> |
<%= link_to 'Back', cpus_path %>