config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :hard_drives
  resources :rams
  resources :cpus
  resources :laptop_brands
  resources :laptop_orders
  resources :laptops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages

  root to: "laptops#index"


  resources :users
end

app/models/laptop_brand.rb
class LaptopBrand < ApplicationRecord
  has_many :laptops

  has_one_attached :picture

  validates :picture, :name, presence: true
end

app/controllers/laptop_brands_controller.rb
class LaptopBrandsController < ApplicationController
  load_and_authorize_resource # run cancancan authorization before every method
  before_action :authenticate_user!
  before_action :set_laptop_brand, only: %i[show edit update destroy]

  # GET /laptop_brands
  # GET /laptop_brands.json
  # Eager load all Laptop Brand entries and send them to INDEX view
  def index
    @laptop_brands = LaptopBrand.with_attached_picture.all
  end

  # GET /laptop_brands/1
  # GET /laptop_brands/1.json
  def show; end

  # GET /laptop_brands/new
  # Create a new empty Laptop brand entry and send it to NEW view
  def new
    @laptop_brand = LaptopBrand.new
  end

  # GET /laptop_brands/1/edit
  def edit; end

  # POST /laptop_brands
  # POST /laptop_brands.json
  def create
    @laptop_brand = LaptopBrand.new(laptop_brand_params)

    # Check if newly created Laptop Brand was saved in database, if it was flash a success message, if not flash a error message
    respond_to do |format|
      if @laptop_brand.save
        format.html { redirect_to @laptop_brand, notice: 'Laptop brand was successfully created.' }
        format.json { render :show, status: :created, location: @laptop_brand }
      else
        format.html { render :new }
        format.json { render json: @laptop_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptop_brands/1
  # PATCH/PUT /laptop_brands/1.json
  def update
    # Check if updated Laptop Brand was saved in database, if it was flash a success message, if not flash a error message
    respond_to do |format|
      if @laptop_brand.update(laptop_brand_params)
        format.html { redirect_to @laptop_brand, notice: 'Laptop brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @laptop_brand }
      else
        format.html { render :edit }
        format.json { render json: @laptop_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptop_brands/1
  # DELETE /laptop_brands/1.json
  def destroy
    @laptop_brand.destroy
    respond_to do |format|
      format.html { redirect_to laptop_brands_url, notice: 'Laptop brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_laptop_brand
    @laptop_brand = LaptopBrand.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def laptop_brand_params
    params.require(:laptop_brand).permit(:picture, :name)
  end
end

app/helpers/laptop_brands_helper.rb
module LaptopBrandsHelper
end

app/views/laptop_brands/_form.html.erb
<%= form_with(model: laptop_brand, local: true) do |form| %>
  <% if laptop_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laptop_brand.errors.count, "error") %> prohibited this laptop_brand from being saved:</h2>

      <ul>
        <% laptop_brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :picture %> 
    <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laptop_brands/edit.html.erb
<h1>Editing Laptop Brand</h1>

<%= render 'form', laptop_brand: @laptop_brand %>

<%= link_to 'Show', @laptop_brand %> |
<%= link_to 'Back', laptop_brands_path %>

app/views/laptop_brands/index.html.erb
<h1>Laptop Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laptop_brands.each do |laptop_brand| %>
      <tr>
        <td>
        <div style="max-height: 50px">
          <% if laptop_brand.picture.attached? %>
            <%= image_tag laptop_brand.picture, class: "brand-logo"%>
          <% end %>  
        </div>
                     
        </td>
        <td><%= laptop_brand.name %></td>
        <td><%= link_to 'Show', laptop_brand %></td>
        <td><%= link_to 'Edit', edit_laptop_brand_path(laptop_brand) %></td>
        <td><%= link_to 'Destroy', laptop_brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laptop Brand', new_laptop_brand_path %>

app/views/laptop_brands/new.html.erb
<h1>New Laptop Brand</h1>

<%= render 'form', laptop_brand: @laptop_brand %>

<%= link_to 'Back', laptop_brands_path %>

app/views/laptop_brands/show.html.erb
<p>
  <strong>Picture:</strong> <br>
  <% if @laptop_brand.picture.attached? %>
    <%= image_tag @laptop_brand.picture %>
  <% end %> 
</p>

<p>
  <strong>Name:</strong>
  <%= @laptop_brand.name %>
</p>

<%= link_to 'Edit', edit_laptop_brand_path(@laptop_brand) %> |
<%= link_to 'Back', laptop_brands_path %>