config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :hard_drives
  resources :rams
  resources :cpus
  resources :laptop_brands
  resources :laptop_orders
  resources :laptops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages

  root to: "laptops#index"


  resources :users
end

app/models/laptop.rb
class Laptop < ApplicationRecord
  enum sold_status: { false: 0, true: 1 }, _prefix: :sold_status

  belongs_to :user

  has_one :laptop_order

  belongs_to :laptop_brand
  belongs_to :grade
  belongs_to :cpu
  belongs_to :ram
  belongs_to :hard_drive

  has_one_attached :picture

  validates :user_id, :laptop_brand_id, :grade_id, :cpu_id, :ram_id, :hard_drive_id, :model, :price, presence: true
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  load_and_authorize_resource # run cancancan authorization before every method
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_laptop, only: %i[show edit update destroy]

  # GET /laptops
  # GET /laptops.json
  # Get all Laptop entries and send them to INDEX view
  def index
    # eager load all laptops
    laptops = Laptop.order('model').includes(:user, :laptop_brand, :grade, :cpu, :ram, :hard_drive).with_attached_picture

    # Get all laptops that ARENT sold and send them to index
    @unsold_laptops = laptops.where(sold_status: 'false')

    # Get all laptops the ARE sold and send them to index
    @sold_laptops = laptops.where(sold_status: 'true')
  end

  # GET /laptops/1
  # GET /laptops/1.json
  def show; end

  # GET /laptops/new
  # Create a new empty Laptop entry and send it to NEW view
  def new
    @laptop = Laptop.new
    # authorize! :create, @laptop
  end

  # GET /laptops/1/edit
  def edit; end

  # POST /laptops
  # POST /laptops.json

  def create
    @laptop = Laptop.new(laptop_params)
    @laptop.user_id = current_user.id
    # Check if newly created Laptop was saved in database, if it was flash a success message, if not flash a error message
    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: 'Laptop was successfully created.' }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1
  # PATCH/PUT /laptops/1.json
  def update
    # Check if updated Laptop was saved in database, if it was flash a success message, if not flash a error message
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: 'Laptop was successfully updated.' }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: 'Laptop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_laptop
    @laptop = Laptop.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def laptop_params
    params.require(:laptop).permit(:user_id, :laptop_brand_id, :grade_id, :Laptop_id, :ram_id, :cpu_id, :hard_drive_id, :model, :price, :sold_status, :picture)
  end
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.erb
<%= form_with(model: laptop, local: true) do |form| %>
  <% if laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
        <% laptop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :picture %> 
    <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <!-- 
  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.where(seller: 'true'), :id, :name, prompt: true) %>
  </div>
  -->

  <div class="field">
    <%= form.label :laptop_brand_id %>
    <%= form.collection_select(:laptop_brand_id, LaptopBrand.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :grade_id %>
    <%= form.collection_select(:grade_id, Grade.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :cpu_id %>
    <%= form.collection_select(:cpu_id, Cpu.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :ram_id %>
    <%= form.collection_select(:ram_id, Ram.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :hard_drive_id %>
    <%= form.collection_select(:hard_drive_id, HardDrive.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <!-- <div class="field">
    <%= form.label :sold_status %>
    <%= form.number_field :sold_status %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laptops/edit.html.erb
<h1>Editing Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Show', @laptop %> |
<%= link_to 'Back', laptops_path %>

app/views/laptops/index.html.erb
<h1>LAPTOPS</h1>

<% if current_or_guest_user.guest == false%>
  <% if current_user.seller == "true" %>
    <%= link_to 'New Laptop', new_laptop_path %>
  <% end %>
<% end %>

<h2>AVAILABLE</h2>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>ID</th>
      <th>Seller</th>
      <th>Brand</th>
      <th>Grade</th>
      <th>Cpu</th>
      <th>Ram</th>
      <th>Hard drive</th>
      <th>Model</th>
      <th>Price</th>
      <th>Sold Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unsold_laptops.each do |laptop| %>
      <tr>
        <td>
          <% if laptop.picture.attached? %>
            <%= image_tag laptop.picture, class: "laptop-image" %>
          <% else %>
            <div class="laptop-backup-image"></div>
          <% end %>
        </td>
        <td><%= laptop.id %></td>
        <td><%= laptop.user.name %></td>
        <td><%= laptop.laptop_brand.name %></td>
        <td><%= laptop.grade.name %></td>
        <td><%= laptop.cpu.name %></td>
        <td><%= laptop.ram.name %></td>
        <td><%= laptop.hard_drive.name %></td>
        <td><%= laptop.model %></td>
        <td><%= laptop.price %></td>
        <td><%= laptop.sold_status %></td>
        <td><%= link_to 'Show', laptop %></td>

        <% if current_or_guest_user.id == laptop.user_id%>
          <td><%= link_to 'Edit', edit_laptop_path(laptop) %></td>
          <td>
            <%= link_to 'Remove', laptop, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% else %>
          <td><%= link_to 'BUY', laptop_orders_path(laptop_order: {laptop_id: laptop.id, user_id: current_or_guest_user.id}), method: :post%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>SOLD</h2>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>ID</th>
      <th>Seller</th>
      <th>Brand</th>
      <th>Grade</th>
      <th>Cpu</th>
      <th>Ram</th>
      <th>Hard drive</th>
      <th>Model</th>
      <th>Price</th>
      <th>Sold Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sold_laptops.each do |laptop| %>
      <tr>
        <td>
          <% if laptop.picture.attached? %>
            <%= image_tag laptop.picture, class: "laptop-image" %>
          <% else %>
            <div class="laptop-backup-image"></div>
          <% end %>
        </td>
        <td><%= laptop.id %></td>
        <td><%= laptop.user.name %></td>
        <td><%= laptop.laptop_brand.name %></td>
        <td><%= laptop.grade.name %></td>
        <td><%= laptop.cpu.name %></td>
        <td><%= laptop.ram.name %></td>
        <td><%= laptop.hard_drive.name %></td>
        <td><%= laptop.model %></td>
        <td><%= laptop.price %></td>
        <td><%= laptop.sold_status %></td>
        <td><%= link_to 'Show', laptop %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/laptops/new.html.erb
<h1>New Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Back', laptops_path %>

app/views/laptops/show.html.erb
<table>
  <thead>
    <tr>
      <th>Picture:</th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td>
          <% if @laptop.picture.attached? %>
            <%= image_tag @laptop.picture, class: "laptop-image" %>
          <% else %>
            <div class="laptop-backup-image"></div>
          <% end %>
        </td>
      </tr>

  </tbody>
</table>

<p>
  <strong>Seller:</strong>
  <%= User.find(@laptop.user_id).name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= LaptopBrand.find(@laptop.laptop_brand_id).name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= Grade.find(@laptop.grade_id).name %>
</p>

<p>
  <strong>Cpu:</strong>
  <%= Cpu.find(@laptop.cpu_id).name %>
</p>

<p>
  <strong>Ram:</strong>
  <%= Ram.find(@laptop.ram_id).name %>
</p>

<p>
  <strong>Hard drive:</strong>
  <%= HardDrive.find(@laptop.hard_drive_id).name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @laptop.model %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @laptop.price %>
</p>

<p>
  <strong>Sold status:</strong>
  <%= @laptop.sold_status %>
</p>

<% if @laptop.sold_status != "true" && @laptop.id == current_or_guest_user.id %>
  <%= link_to 'Edit', edit_laptop_path(@laptop) %> |
<% end %>
<%= link_to 'Back', laptops_path %>