config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :hard_drives
  resources :rams
  resources :cpus
  resources :laptop_brands
  resources :laptop_orders
  resources :laptops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages

  root to: "laptops#index"


  resources :users
end

app/views/layouts/_admin_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">REFURBISHED LAPTOPS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "ADMIN PANEL", rails_admin_path, class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href=<%= laptops_path %>>LAPTOPS</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          LAPTOP COMPONENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-item">
            <%= link_to "LAPTOP ORDERS", laptop_orders_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "BRANDS", laptop_brands_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "CPUS", cpus_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "RAMS", rams_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "HARD DRIVES", hard_drives_path %>
          </div>

          <%# <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> %>
        </div>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> %>
    </ul>

    <!-- LOGIN GREETING -->
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if user_signed_in? %>
          <%= "Hello! ID: #{current_or_guest_user.id}, NAME: #{current_or_guest_user.name}, EMAIL: #{current_or_guest_user.email}, SELLER STATUS: #{current_or_guest_user.seller}, ADMIN: #{current_or_guest_user.admin} " %>
        <% end %> 
      </div>
      <div class="navbar-nav">
        <!-- LINK TO MY PROFILE ONLY IF USER IS LOGGED IN AND NOT A GUEST -->
        <% if current_or_guest_user.guest == false %>
          <div class="nav-item">
            <a class="nav-link" href=<%= user_path(current_or_guest_user.id) %>>MY PROFILE</a>
          </div>
        <% end %>

        <% unless user_signed_in? %>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-primary ml-1' %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary ml-1' %>
        <% else %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">REFURBISHED LAPTOPS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= pages_path %>>HOME <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= users_path %>>USERS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= laptops_path %>>LAPTOPS</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          LAPTOP COMPONENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-item">
            <%= link_to "LAPTOP ORDERS", laptop_orders_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "BRANDS", laptop_brands_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "CPUS", cpus_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "RAMS", rams_path %>
          </div>

          <div class="dropdown-item">
          <%= link_to "HARD DRIVES", hard_drives_path %>
          </div>

          <%# <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> %>
        </div>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> %>
    </ul>

    <!-- LOGIN GREETING -->
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if user_signed_in? %>
          <%= "Hello! ID: #{current_user.id}, NAME: #{current_user.name}, EMAIL: #{current_user.email}, SELLER STATUS: #{current_user.seller}, ADMIN: #{current_user.admin} " %>
        <% end %> 
      </div>
      <div class="navbar-nav">
        <% unless user_signed_in? %>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-primary ml-1' %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary ml-1' %>
        <% else %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/_user_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">REFURBISHED LAPTOPS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= laptops_path %>>LAPTOPS</a>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> %>
    </ul>

    <!-- LOGIN GREETING -->
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">

      </div>
      <div class="navbar-nav">
        <!-- LINK TO MY PROFILE ONLY IF USER IS LOGGED IN AND NOT A GUEST -->
        <% if current_or_guest_user.guest == false %>
          <div class="nav-item">
            <a class="nav-link" href=<%= user_path(current_or_guest_user.id) %>>MY PROFILE</a>
          </div>
        <% end %>

        <% unless user_signed_in? %>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-outline-primary ml-1' %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary ml-1' %>
        <% else %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1' %>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>refurbished-laptop-marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_or_guest_user.admin == false%>
      <%= render "layouts/user_nav" %>
    <% else %>
      <%= render "layouts/admin_nav" %>
    <% end %>

    <% if user_signed_in? %>
      <%= "Hello! ID: #{current_or_guest_user.id}, NAME: #{current_or_guest_user.name}, EMAIL: #{current_or_guest_user.email}, SELLER STATUS: #{current_or_guest_user.seller}, ADMIN: #{current_or_guest_user.admin} " %>
    <% end %> 

    

    <%= render "layouts/alerts" %>

    <%= yield %>

  </body>
</html>